name: Weekly Chart Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: '15 0 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout with creds so we can push later
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) install Node
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) install our npm libs
      - run: npm install spotify-web-api-node firebase-admin googleapis

      # 4) build the JSON
      - name: Build charts JSON
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          SPOTIFY_CLIENT_ID:     ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          YOUTUBE_API_KEY:       ${{ secrets.YOUTUBE_API_KEY }}
        run: node scripts/buildCharts.js

      # 5) commit & push only if JSON changed
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/mash100.json public/masha50.json
          if ! git diff --cached --quiet; then
            git commit -m "Weekly charts update"
            git push origin main
          else
            echo "No changes to commit"
          fi

      # 6) deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId:              live
