name: Weekly Chart Update

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch: {}
  schedule:
    - cron: '15 0 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: main

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install spotify-web-api-node firebase-admin googleapis

      - name: Build charts JSON
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          SPOTIFY_CLIENT_ID:        ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET:    ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          YOUTUBE_API_KEY:          ${{ secrets.YOUTUBE_API_KEY }}
        run: node scripts/buildCharts.js

      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add public/mash100.json public/masha50.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Weekly charts update"
            git push origin main
          fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId:              mashstat-vote
          channelId:              live
